// Generated by gencpp from file robot/ticks.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_TICKS_H
#define ROBOT_MESSAGE_TICKS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct ticks_
{
  typedef ticks_<ContainerAllocator> Type;

  ticks_()
    : right_wheel(0.0)
    , left_wheel(0.0)  {
    }
  ticks_(const ContainerAllocator& _alloc)
    : right_wheel(0.0)
    , left_wheel(0.0)  {
  (void)_alloc;
    }



   typedef float _right_wheel_type;
  _right_wheel_type right_wheel;

   typedef float _left_wheel_type;
  _left_wheel_type left_wheel;




  typedef boost::shared_ptr< ::robot::ticks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::ticks_<ContainerAllocator> const> ConstPtr;

}; // struct ticks_

typedef ::robot::ticks_<std::allocator<void> > ticks;

typedef boost::shared_ptr< ::robot::ticks > ticksPtr;
typedef boost::shared_ptr< ::robot::ticks const> ticksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::ticks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::ticks_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot': ['/home/kartik/catkin_ws/src/robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::ticks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::ticks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::ticks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::ticks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::ticks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::ticks_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8a0d6fe18087fd03841f81076bfc858";
  }

  static const char* value(const ::robot::ticks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8a0d6fe18087fd0ULL;
  static const uint64_t static_value2 = 0x3841f81076bfc858ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/ticks";
  }

  static const char* value(const ::robot::ticks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 right_wheel\n\
float32 left_wheel\n\
\n\
";
  }

  static const char* value(const ::robot::ticks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::ticks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.right_wheel);
      stream.next(m.left_wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ticks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::ticks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::ticks_<ContainerAllocator>& v)
  {
    s << indent << "right_wheel: ";
    Printer<float>::stream(s, indent + "  ", v.right_wheel);
    s << indent << "left_wheel: ";
    Printer<float>::stream(s, indent + "  ", v.left_wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_TICKS_H
